apiVersion: v1
kind: Service
metadata:
  name: hello-rancher
  namespace: demo-rancher
spec:
  type: NodePort
  selector:
    app: hello-rancher
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30002
